# Generated by Django 4.1.3 on 2022-11-24 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('father', models.CharField(max_length=20)),
                ('fnumber', phone_field.models.PhoneField(max_length=15)),
                ('mother', models.CharField(max_length=20)),
                ('mnumber', phone_field.models.PhoneField(max_length=15)),
                ('age', models.FloatField(max_length=5)),
                ('weight', models.FloatField(max_length=5)),
                ('height', models.FloatField(max_length=5)),
                ('headcir', models.FloatField(max_length=5)),
                ('muac', models.FloatField(max_length=5)),
                ('chestCir', models.FloatField(max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('referredto', models.CharField(blank=True, max_length=50, null=True)),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
