# Generated by Django 4.1.3 on 2022-11-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_profile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
