# Generated by Django 4.1.3 on 2022-11-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_child_id_child_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='adder',
            field=models.CharField(max_length=50),
        ),
    ]
