# Generated by Django 4.1.3 on 2022-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_child_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='fName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
