# Generated by Django 4.1.3 on 2022-11-29 14:20

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_id', models.AutoField(primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=20)),
                ('lName', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('father', models.CharField(max_length=20)),
                ('fnumber', phone_field.models.PhoneField(max_length=15)),
                ('mother', models.CharField(max_length=20)),
                ('mnumber', phone_field.models.PhoneField(max_length=15)),
                ('age', models.FloatField(max_length=5)),
                ('weight', models.FloatField(max_length=5)),
                ('height', models.FloatField(max_length=5)),
                ('headcir', models.FloatField(max_length=5)),
                ('muac', models.FloatField(max_length=5)),
                ('chestCir', models.FloatField(max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('diagnosis', models.CharField(blank=True, max_length=50, null=True)),
                ('referredto', models.CharField(blank=True, max_length=50, null=True)),
                ('adder', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
    ]
