# Generated by Django 4.1.3 on 2022-12-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_child_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='slug',
            field=models.SlugField(default='test-profile'),
            preserve_default=False,
        ),
    ]
